-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

class "TestActor" (CharClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = 1;
    placementRandomRotation = false;

    height = 1.808;
    radius = 0.393;

    camAttachPos = vector3(0,0,0.854);
}

