-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

local mass = 75

class "TestActor" (CharClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = 1;
    placementRandomRotation = false;

    camPos = vector3(0,0,0);
    moveInfo = {
        forwards = mass*10;
        backwards = mass*10;
        strafeLeft = mass*10;
        strafeRight = mass*10;
        jump = mass*10;
    }
}

