-- Lua file generated by Blender class export script.
-- WARNING: If you modify this file, your changes will be lost if it is subsequently re-exported from blender

class "Slope68" (ColClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = false;
    placementRandomRotation = false;
}

class "Slope56" (ColClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = false;
    placementRandomRotation = false;
}

class "Slope45" (ColClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = false;
    placementRandomRotation = false;
}

class "Slope34" (ColClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = false;
    placementRandomRotation = false;
}

class "Slope22" (ColClass) {
    renderingDistance = 100.0;
    castShadows = true;
    placementZOffset = false;
    placementRandomRotation = false;
}

